### ISSUE TITLE
fabric already defined

### ISSUE THREAD

**Issue by vmsreeram** [vmsreeram/moodle-qtype_essayannotate#20]
warning

**Comment by nideez45** [comment]
![image](https://github.com/vmsreeram/moodle-qtype_essayannotate/assets/75631297/9b7924c6-4a3a-46fe-a0b4-4bf03fd77e47)
In production environment, all the js files are bundled into a single first.js sent on every pageload, but there is also a duplicate request - typically event.js which has same the content. Since fabric warns when some objects of it get redefined, it is shown in console. So to avoid this we suppressed the warning message. 

![image](https://github.com/vmsreeram/moodle-qtype_essayannotate/assets/75631297/68e7671b-7583-4355-a21f-35c02ca8d59d)
